#!/usr/bin/env bash
# This script reads /etc/passwd line by line and displays specific fields using a while loop
while IFS=: read -r username _ uid _ _ home _
do
    echo "$username:$uid:$home"
done < /etc/passwd
