#!/usr/bin/env bash
# This script loops 10 times, printing "Best School", and adds "Hi" on the 9th loop
counter=1
while [ "$counter" -le 10 ]
do
    echo "Best School"
    if [ "$counter" -eq 9 ]
    then
        echo "Hi"
    fi
    counter=$((counter + 1))
done
