#!/usr/bin/env bash
VAL_WATER=$(echo "$WATER" | tr 'water' '01234')
VAL_STIR=$(echo "$STIR" | tr 'stir.' '01234')
RESULT_BASE8=$(echo "ibase=5; obase=8; $VAL_WATER + $VAL_STIR" | bc)
echo "$RESULT_BASE8" | tr '01234567' 'bestchol'
