#!/usr/bin/env bash
# This script prints a message indefinitely and traps SIGTERM signals cleanly

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2 &
    wait $!
done
