#!/usr/bin/env bash
# This script prints a message indefinitely and flushes SIGTERM traps immediately

trap 'printf "I am invincible!!!\n"' SIGTERM

while true
do
    echo "To infinity and beyond"
    sleep 2
done
